# Generated by Django 4.0.3 on 2022-04-15 16:01

import django.core.validators
from django.db import migrations, models
import hoteliers.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=75, null=True, validators=[django.core.validators.MinLengthValidator(2), hoteliers.common.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
