# Generated by Django 4.0.3 on 2022-04-15 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_hotel_description_alter_hotel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
