# Generated by Django 4.0.3 on 2023-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_hotel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
