# Generated by Django 4.0.3 on 2023-08-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_hotel_gallery_photos_hotelgalleryphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='gallery_photos',
        ),
    ]
