# Generated by Django 4.0.3 on 2023-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_hotel_gallery_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgalleryphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
