# Generated by Django 4.0.3 on 2023-08-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_hotelgalleryphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelgalleryphoto',
            old_name='hotel',
            new_name='owned_by_hotel',
        ),
    ]
